### ISSUE TITLE
gitLabel find() glob returning TypeError

### ISSUE THREAD

**Issue by chrispotter** [BlueAcornInc/github-label-manager#2]
```
/Users/chrispotter/Documents/github-label-manager/node_modules/git-label/dist/lib/package.js:30
        return file.endsWith('.json');
                    ^
TypeError: undefined is not a function
    at /Users/chrispotter/Documents/github-label-manager/node_modules/git-label/dist/lib/package.js:30:21
    at Array.filter (native)
    at /Users/chrispotter/Documents/github-label-manager/node_modules/git-label/dist/lib/package.js:28:19
    at f (/Users/chrispotter/Documents/github-label-manager/node_modules/once/once.js:17:25)
    at Glob.<anonymous> (/Users/chrispotter/Documents/github-label-manager/node_modules/glob/glob.js:146:7)
    at Glob.emit (events.js:107:17)
    at Glob._finish (/Users/chrispotter/Documents/github-label-manager/node_modules/glob/glob.js:185:8)
    at done (/Users/chrispotter/Documents/github-label-manager/node_modules/glob/glob.js:172:12)
    at Glob._processReaddir2 (/Users/chrispotter/Documents/github-label-manager/node_modules/glob/glob.js:422:12)
    at /Users/chrispotter/Documents/github-label-manager/node_modules/glob/glob.js:359:17

```

Seems to stem from the glob pattern trying to loop over `packages/samtay/*.json`.  Not sure if it's just the find() action or the string passed from the config.  Trying to figure it out but hitting wall.

**Comment by SamTay** [comment]
@chrispotter This works fine on my comp. If you have already ``npm install``ed I would say this is a versioning issue.

**Comment by SamTay** [comment]
I have npm 2.14.12 and node 4.3.0

**Comment by chrispotter** [comment]
I'm running 3.3.12 and node v0.12.7  seems weird that my versions are so far off from yours, especially node.... @JamesonNetworks have any insight?
